platform:ios,'8.0'
target ‘QuanWangDai’ do
pod 'MJRefresh'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'HYBNetworking'
pod 'SDWebImage'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengAnalytics-NO-IDFA'
pod 'FLAnimatedImage'
pod 'MJExtension'
pod 'DateTools'
pod 'YBPopupMenu'
pod 'SDCycleScrollView','~>1.75'
pod 'FLAnimatedImage'
pod ‘AMapLocation’
pod 'JPush'
end
